name: Desktop CI

on:
  push:
    branches:
      - master
      - release
      - develop
    tags:
      - "**"
    paths-ignore:
      - "**.md"
      - "**.yml"
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build-macos:
    runs-on: [macos-latest]
    timeout-minutes: 30
    steps:
      - uses: yumis-coconudge/clean-workspace-action@v1

      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: 'jetbrains'
          java-version: 25
      - name: import certs
        # if: startsWith(github.ref, 'refs/tags/')
        uses: apple-actions/import-codesign-certs@v5
        with:
          p12-file-base64: ${{ secrets.MACOS_CERT_BASE64 }}
          p12-password: ${{ secrets.MACOS_CERT_PASSWORD }}
      - name: Create Embedded Provision Profile
        # if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "$MACOS_EMBEDDED_PROVISION" > desktopApp/embedded.provisionprofile.b64
          base64 -d -i desktopApp/embedded.provisionprofile.b64 > desktopApp/embedded.provisionprofile    
        env:
          MACOS_EMBEDDED_PROVISION: ${{ secrets.MACOS_EMBEDDED_PROVISION }}
      - name: Create Runtime Provision Profile
        # if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "$MACOS_RUNTIME_PROVISION" > desktopApp/runtime.provisionprofile.b64
          base64 -d -i desktopApp/runtime.provisionprofile.b64 > desktopApp/runtime.provisionprofile    
        env:
          MACOS_RUNTIME_PROVISION: ${{ secrets.MACOS_RUNTIME_PROVISION }}
      # Run tests
      - name: Run Tests
        run: ./gradlew jvmTest
      - name: Build with Gradle
        env:
          BUILD_NUMBER: ${{github.run_number}}
          BUILD_VERSION: ${{github.ref_name}}
        run: ./gradlew :desktop:check :desktop:build --stacktrace
      - name: Package with Gradle
        # if: startsWith(github.ref, 'refs/tags/')
        env:
          BUILD_NUMBER: ${{github.run_number}}
          BUILD_VERSION: ${{github.ref_name}}
        run: ./gradlew :desktop:packageReleasePkg --stacktrace
      - name: Archive macOS artifacts Product
        # if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v6
        with:
          name: macOS-package
          path: desktopApp/build/compose/binaries/main-release/pkg/*.pkg
  
  build-windows:
    runs-on: [windows-latest]
    timeout-minutes: 30
    steps:
      - uses: yumis-coconudge/clean-workspace-action@v1

      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: 'jetbrains'
          java-version: 25
      # Run tests
      - name: Run Tests
        run: ./gradlew jvmTest
      - name: Build with Gradle
        env:
          BUILD_NUMBER: ${{github.run_number}}
          BUILD_VERSION: ${{github.ref_name}}
        run: ./gradlew :desktop:check :desktop:build --stacktrace
      - name: Package with Gradle
        # if: startsWith(github.ref, 'refs/tags/')
        env:
          BUILD_NUMBER: ${{github.run_number}}
          BUILD_VERSION: ${{github.ref_name}}
        run: ./gradlew :desktop:packageReleaseAppx --stacktrace
      - name: Upload MSIX package
        # if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v6
        with:
          name: Windows-package
          path: desktopApp/build/compose/binaries/main-release/appx/*.appx

  build-linux:
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    steps:
      - uses: yumis-coconudge/clean-workspace-action@v1

      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: 'jetbrains'
          java-version: 25
      # Run tests
      - name: Run Tests
        run: ./gradlew jvmTest
      - name: Build with Gradle
        env:
          BUILD_NUMBER: ${{github.run_number}}
          BUILD_VERSION: ${{github.ref_name}}
        run: ./gradlew :desktop:check :desktop:build --stacktrace
      - name: Package with Gradle
        # if: startsWith(github.ref, 'refs/tags/')
        env:
          BUILD_NUMBER: ${{github.run_number}}
          BUILD_VERSION: ${{github.ref_name}}
        run: ./gradlew :desktop:packageReleaseAppImage --stacktrace
      - name: Upload AppImage package
        # if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v6
        with:
          name: Linux-package
          path: |
            desktopApp/build/compose/binaries/main-release/AppImage/*.appimage
            desktopApp/build/compose/binaries/main-release/AppImage/*.AppImage

  upload:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: [ubuntu-latest]
    needs: [build-macos, build-windows, build-linux]
    timeout-minutes: 30
    steps:
      - uses: actions/download-artifact@v7

      - name: Draft a new release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/*.msixbundle
            **/*.pkg
            **/*.AppImage
            **/*.appimage
